# Generated by Django 5.0.14 on 2026-05-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Téléphone'),
        ),
    ]
