# Generated by Django 4.2.30 on 2026-07-01 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garages', '0004_garage_is_active_alter_garage_opening_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('period', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], max_length=15, unique=True, verbose_name='Période')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix (FCFA)')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Durée (jours)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Formule',
                'verbose_name_plural': 'Formules',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('actif', 'Actif'), ('expire', 'Expiré'), ('annule', 'Annulé')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='garages.garage', verbose_name='Garage')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscription.plan', verbose_name='Formule')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (FCFA)')),
                ('method', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money')], max_length=20, verbose_name='Moyen de paiement')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro Mobile Money')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('operator_ref', models.CharField(blank=True, max_length=100, verbose_name='Référence opérateur')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence interne')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Confirmé par')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscription.subscription', verbose_name='Abonnement')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
