# Generated by Django 5.0.14 on 2026-05-12 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du service')),
                ('slug', models.SlugField(help_text="Identifiant unique pour l'URL", unique=True, verbose_name='URL Slug')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône (classe CSS ou emoji)')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GarageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_starting_at', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix à partir de')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='garages.garage')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Service de Garage',
                'verbose_name_plural': 'Services de Garage',
                'unique_together': {('garage', 'service')},
            },
        ),
    ]
