# Generated by Django 5.0.14 on 2026-05-14 22:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garages', '0003_remove_garage_garages_gar_city_bc40d8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='De 1 (mécontent) à 5 (excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('title', models.CharField(blank=True, help_text='Résumé de votre avis (optionnel)', max_length=100, verbose_name='Titre')),
                ('comment', models.TextField(help_text='Partagez votre expérience', max_length=1000, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Cochez si le client a réellement utilisé le service', verbose_name='Avis vérifié')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='garages.garage', verbose_name='Garage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['garage', '-rating'], name='reviews_rev_garage__b2b2f1_idx'), models.Index(fields=['-created_at'], name='reviews_rev_created_03e07d_idx')],
                'unique_together': {('garage', 'user')},
            },
        ),
    ]
