# Generated by Django 5.0.14 on 2026-05-12 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du Garage')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=255, verbose_name='Adresse complète')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Code postal')),
                ('website', models.URLField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True, verbose_name='Ouvert actuellement')),
                ('opening_hours', models.TextField(help_text='Ex: Lun-Ven: 8h-18h, Sam: 9h-12h', verbose_name="Horaires d'ouverture")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='garages/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='garages/banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garage_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Garage',
                'verbose_name_plural': 'Garages',
                'indexes': [models.Index(fields=['city'], name='garages_gar_city_bc40d8_idx')],
            },
        ),
    ]
