# Generated by Django 5.0.14 on 2026-05-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0002_garage_phone_number'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='garage',
            name='garages_gar_city_bc40d8_idx',
        ),
        migrations.AlterField(
            model_name='garage',
            name='opening_hours',
            field=models.TextField(verbose_name="Horaires d'ouverture"),
        ),
    ]
