# Generated by Django 4.2.30 on 2026-07-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0003_remove_garage_garages_gar_city_bc40d8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Activé automatiquement après validation du paiement.', verbose_name='Visible sur la plateforme'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='opening_hours',
            field=models.TextField(blank=True, verbose_name="Horaires d'ouverture"),
        ),
    ]
